### ISSUE TITLE
"/usr/bin/env python2" in mkimage/imagetool-uncompressed.py won't work on most systems

### ISSUE THREAD

**Issue by benosteen** [raspberrypi/tools#1]
Most systems don't have an executable called 'python2' and so env won't find it if you try to run it directly, eg:

    $ ./imagetool-uncompressed.py <foo> 
    /usr/bin/env: python2: No such file or directory

fails, whereas

    python imagetool-uncompressed.py <foo> 

works.

**Comment by Ruffio** [comment]
@benosteen is this still an issue?

**Comment by benosteen** [comment]
To be honest, it's been such a long time I have no idea!

**Comment by popcornmix** [comment]
imagetool-uncompressed.py is no longer required for building the kernel, so i guess the issue is unimportant.
