### ISSUE TITLE
There isn't a float64x2_t type in arm_neon.h

### ISSUE THREAD

**Issue by codenew0** [raspberrypi/tools#100]
I want to convert my codes from Intel architecture to Raspbain. I used **__m128d** which is same as float64x2_t, and a lot of Intel Intrinsics like "_mm_sub_sd". These can be easily rewrite by "arch64/arm_neon.h" cause it has float64x2_t type with Intrinsics like "vsubq_f64". So what should I do if I wanna use this data type.

**Comment by popcornmix** [comment]
This isn't the right place for this question. This repo just hosts a prebuilt gcc without changes.
The forum might be a better place for this question.
