### ISSUE TITLE
make armstub8-gic.bin Circular dependency dropped

### ISSUE THREAD

**Issue by sebastianwagner** [raspberrypi/tools#101]
When running `LANG=C PATH=$PATH:$TOOLCHAIN/bin make armstub8-gic.bin`
i get
```
make: Circular armstub8-gic.C <- armstub8-gic.bin dependency dropped.
./bin2c bin2c > armstub8-gic.C
g++    -c -o armstub8-gic.o armstub8-gic.C
armstub8-gic.C:1:3: error: expected unqualified-id before numeric constant
   0x464C457F, 0x00010102, 0x00000000, 0x00000000, 0x003E0003, 0x00000001, 0x000010A0, 0x00000000,
   ^~~~~~~~~~
make: *** [<builtin>: armstub8-gic.o] Error 1
rm armstub8-gic.C
```
My `$TOOLCHAIN/bin` points among other to some recent _aarch64-linux-gnu-gcc-9.2.0_ but not _g++_.
With repo pointing to current _master_ 5caa704.
Does this relate to me using the wrong version of g++?
What can i do to force make using tools and compiler from a different prefix?
Could you release pre-built armstub files for different raspberry-pib models?

**Comment by popcornmix** [comment]
That isn't current master. It's 18 months old.
This is master: https://github.com/raspberrypi/tools/commit/49719d5544cd33b8c146235e1420f68cd92420fe
