### ISSUE TITLE
Cross compiling for raspbian on MacOS

### ISSUE THREAD

**Issue by aaronbuchwald** [raspberrypi/tools#106]
I'm currently trying to cross-compile for raspberry pi on MacOS within FPrime: https://github.com/nasa/fprime/tree/master/RPI. Currently, trying to utilize the compiler here, but getting the error that my computer cannot execute the binary file: https://github.com/raspberrypi/tools/blob/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc

Is there a way to fix this or is this simply not compatible with MacOS?

**Comment by dlech** [comment]
It is not compatible. You can use something like Docker or VirtualBox to run Linux on your Mac.
