### ISSUE TITLE
ld: cannot find -li2c

### ISSUE THREAD

**Issue by davxiao** [raspberrypi/tools#111]
Target platform: Pi Zero W
Compiler platform: Ubuntu

Everything else worked, but the linker was complaining about not being able to locate this lib: `i2c`. 

I was trying to compile this library `https://github.com/hallard/ArduiPi_OLED`
Any suggestions? Thanks.

**Comment by pelwell** [comment]
Your question is answered here: https://github.com/hallard/ArduiPi_OLED/issues/19

**Comment by popcornmix** [comment]
Closing as i2c isn't part of the toolchain.
