### ISSUE TITLE
ld search path for arm cross compilers include host system paths

### ISSUE THREAD

**Issue by cr1901** [raspberrypi/tools#15]
Hello all,

To be honest, I'm not certain this is actually a bug, as I only use the cross tools for distcc, but I noticed that running ld --verbose* arshows that the cross-ld attempts to search for libraries on the hosts' system path:

```
 /opt/rpi_tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-ld --verbose | less
GNU ld (crosstool-NG linaro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11) 2.24.0.2013
1220
  Supported emulations:
   armelf_linux_eabi
   armelfb_linux_eabi
using internal linker script:
==================================================
/* Script for -z combreloc: combine and sort reloc sections */
OUTPUT_FORMAT("elf32-littlearm", "elf32-bigarm",
              "elf32-littlearm")
OUTPUT_ARCH(arm)
ENTRY(_start)
SEARCH_DIR("=/usr/local/lib/arm-linux-gnueabihf"); SEARCH_DIR("=/usr/local/lib")
; SEARCH_DIR("=/lib/arm-linux-gnueabihf"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/us
r/lib/arm-linux-gnueabihf"); SEARCH_DIR("=/usr/lib");
```

I imagine most people using the cross-compilers are using them in conjunction with distcc, so this issue wouldn't manifest itself much in practice. However, for those who are attempting to build and link on an x86 machine before sending their code off to the Pi, I can't help but wonder that ld will attempt to link against x86 libraries with the same name as arm libraries. The search path provides an opportunity for x86 libraries to be found before arm libraries, especially in /usr/local/lib.

However, again, I do not know for sure, if this is a bug. ld, the gcc compiler driver, and the toolchain itself may be manipulating paths in ways that I don't see, and currently I'm not in a position to test by cross-compiling a libc. I'm simply asking if the ld search path as-is is intentional.

Thanks for any clarification!

*Some perspective: I'm trying to build a freestanding cross gcc that doesn't depend on a target c stdlib. One issue I've noticed is that libssp must be disabled in such cases. Yet these arm cross compilers have libssp enabled (of course, they can be used in "freestanding mode", a la distcc without pump :P, but still), so I was attempting to look for the libc which the arm cross compilers link against in the linker script.

**Comment by Ruffio** [comment]
@cr1901 is this still an issue?

**Comment by cr1901** [comment]
@Ruffio I believe I concluded that it's "not a bug"/"by design", but as I do not currently run Linux on my Pi, I am unable to test. Go ahead and close.
