### ISSUE TITLE
how to connect usb?

### ISSUE THREAD

**Issue by pwl42** [raspberrypi/tools#33]
straight through or crossover?

**Comment by Ruffio** [comment]
@pwl42 whats the issue here?

**Comment by pwl42** [comment]
when you connect the usb ports together do you connect them D+ to D+ and D- to D- ?
or, do you cross them like a null modem cable or a crossover ethernet cable?

**Comment by popcornmix** [comment]
This is nothing to do with raspberry pi tool repo. Ask in the forum.
