### ISSUE TITLE
c++11 compiler specifications

### ISSUE THREAD

**Issue by groolot** [raspberrypi/tools#34]
It seems that the compiler does not implement ``c++11`` standard language as ``-std=c++11`` but only with ``-std=c++0x`` with the defined macro ``__cplusplus != 201103L``.

How can we use the ``c++11`` standard with this compiler ?

**Comment by Annonomus-Penguin** [comment]
If I recall correctly, older versions of GCC require `c++0x` whereas newer ones use `c++11x`. Thus, I think it is the version of GCC that determines the type you use.

**Comment by popcornmix** [comment]
Are you talking about the gcc cross compiler in this repo?
``echo "int x;" > x.cpp && arm-linux-gnueabihf-gcc -c -std=c++11 x.cpp``
runs without complaint for me.

**Comment by Ruffio** [comment]
@groolot any update/clarification on this issue?

**Comment by popcornmix** [comment]
I've added linaro gcc 4.9.3 to tools repo.
I suspect this can be closed.
