### ISSUE TITLE
rpiboot fail to upload buildroot.elf + fatimage when fatimage is larger than a few MB

### ISSUE THREAD

**Issue by grochefort** [raspberrypi/tools#39]
First, there is no problem with msd.elf turning the device in mass storage device.
I am using a compute module with its board, problem comes with the transfer of both buildroot.elf and fatimage that fail with (large) fatimage file.

Following readme in test_code lead to generate a default fatimage file which is 20MB. 
Here are the result I get with rpiboot and such an image :

```
$ sudo ./rpiboot -v -b fatimage -x ../test_code/test_code 
Waiting for BCM2835 ...
Found serial = 0: writing file ./usbbootcode.bin
libusb_bulk_transfer returned 0
Writing 16674 bytes
libusb_bulk_transfer returned 0
Successful
Waiting for BCM2835 ...
Found serial = 1: writing file ./buildroot.elf
Adding 20635648 bytes of binary to end of elf
libusb_bulk_transfer returned 0
Writing 21609448 bytes
libusb_bulk_transfer returned -1
Failed to read correct length, returned 24
```

Seems that it is not the libusb_bulk_transfer which failed first but rather libusb_control_transfer (-7 / timeout ) but the returned error code is not handle (main.c:54)

The same command line seems to succeed when the fatimage is less than 8MB.

**Comment by ghollingworth** [comment]
With latest https://github.com/raspberrypi/usbboot.git this is no longer a problem...
