### ISSUE TITLE
-std=c++14 support 

### ISSUE THREAD

**Issue by jvcleave** [raspberrypi/tools#40]
Raspbian Jessie is able to support the `-std=c++14 ` flags but these tools don't understand it. 

Sorry if this is a duplicate as github doesn't allow for searching of the + character

**Comment by popcornmix** [comment]
I've added linaro gcc 4.9.3 to tools repo.
@jvcleave does that work for you?

**Comment by jvcleave** [comment]
I found [another solution](https://gist.github.com/jvcleave/8489b3ec5897eb1a26a2) in the meantime but good to know it has been updated

**Comment by jvcleave** [comment]
Thanks! I found [another solution](https://gist.github.com/jvcleave/ed342fb2d41564bcdab6) in the meantime but good to know it has been updated
