### ISSUE TITLE
Usb boot could be updated.

### ISSUE THREAD

**Issue by ED6E0F17** [raspberrypi/tools#44]
It would be nice to be able to boot a model A from usb, but there may be issues with usbboot/buildroot.elf expecting 512Mb of ram.

The supplied usbboot/buildroot.elf is over 12 months old, and should be updated more frequently to support the latest hardware and kernel features.

VC_BUILD_ID_TIME: Oct 28 2014

EDIT: It is fairly obvious that this should work with the Model A, with the right kernel, but I am currently getting Seven Flashes at boot, for Kernel Not Found, even with an older kernel.

**Comment by popcornmix** [comment]
ping @ghollingworth

**Comment by ghollingworth** [comment]
I'm in the process of creating a new filesystem boot mechanism which means that we'll not require buildroot.elf and instead use the standard start.elf

Watch this space...

Gordon

**Comment by AndyPi** [comment]
Hi, 
I have been trying to follow instructions but they dont work.  Aim is to boot the Pi0 from USB and then use ethernet over usb connectivity.  Any news or ETA.  

After hacking the patch to get the USB bits into buildroot config the compile fails with 
> of_find_device_by_node" [drivers/misc/bcm2835_smi.ko] undefined!
Im thinking the linux config is out of date. 

regards...

**Comment by ghollingworth** [comment]
Not being able to build buildroot isn't a part of this, I am not going to keep the patch up to date for all buildroot versions.  I'd suggest understanding the changes I had to make to buildroot to get it to build and then implementing those on a recent version.  The linux config will be a year or more out of date now...

Gordon

**Comment by ED6E0F17** [comment]
"Someone" should update the buildroot patch to copy across the device tree files - but it is quite hard to test before the firmware is updated.

It would be nice to net-boot Raspbian over USB without an sdcard.

**Comment by Gadgetoid** [comment]
@AndyPi I've not been able to boot anything on the Pi0 over USB, I believe `usbbootcode.bin` simply doesn't support it at the moment. I know the tool works because I've tried it with a raw, VideoCore "blink" binary compiled with vasm, but `usbbootcode.bin` simply doesn't cause the re-enumeration and serial port increment that the tool expects.

I'm eagerly awaiting an updated version.

Apparently this already works for running custom binaries ( for baremetal tinkering ) on A+/CM, but not on the Zero: https://github.com/dwelch67/raspberrypi/issues/15

**Comment by AndyPi** [comment]
Hi 
thanks for the reply, maybe I'm not going mad !  I too believe that the failure to re-enumerate to serial=1 causes the (potentially) infinite wait.

**Comment by ED6E0F17** [comment]
Any news on Pi Zero support? Should the CM3 update work if I add device tree files to my "buildroot" ?

**Comment by Gadgetoid** [comment]
The new CM3 update certainly causes the Pi Zero to re-enumerate to serial 1 and allow code to be uploaded, however I've got no further with getting code to run. `rpiboot` concats the FAT image I'm generating onto the end of `buildroot.elf` before uploading, so I'm inclined to think that the out-of-date `buildroot.elf` is now the culprit, but I'm honestly somewhat out of my depth here and clutching at straws!

**Comment by AndyPi** [comment]
@ghollingworth 
>
I'm in the process of creating a new filesystem boot mechanism which means that we'll not require buildroot.elf and instead use the standard start.elf
Watch this space...
> 

Is there any news on new boot mechanism which avoids buildroot.  It would be very useful.  

regards
Andy

**Comment by lurch** [comment]
> I am not going to keep the patch up to date for all buildroot versions

That's fair enough, but it might be useful if the docs gave a buildroot git commit-hash for when your buildroot patch _was_ working :-)

**Comment by ghollingworth** [comment]
I'm going to update this system completely in the next few days (all being well) which means this'll all get a lot easier, meaning no buildroot patch required anymore!
