### ISSUE TITLE
Buildroot + toolchain -- kernel too old

### ISSUE THREAD

**Issue by samnazarko** [raspberrypi/tools#5]
If I use Buildroot with the new hardfp i386 toolchain and the rpi-patches branch I get kernel too old error. I had to use the older x64 hardfp toolchain to get past this error. I didn't do so, but if you run file on a binary you will see the target kernel version. 

You should compile glibc with --enable-kernel

**Comment by Ruffio** [comment]
@samnazarko is this still an issue?

**Comment by samnazarko** [comment]
I no longer cross compile nor use Pi toolchains for building OSMC / Raspbmc.

However -- the toolchain seems modern. If you have issues, let @popcornmix know and I am sure he can resolve your problems.

Sam

**Comment by NEOM-ivar** [comment]
Old post, seemingly timeless issue. I did run into this today, and googling led me to this post.

The trick is that selecting the linux version for the toolchain is separate from selecting the kernel to build and run.
[Toolchain -> Kernel Headers -> x.xx]
[Kernel -> Kernel version]

Happy now
