### ISSUE TITLE
usbboot LIBUSB_LOG_LEVEL_WARNING undeclared

### ISSUE THREAD

**Issue by otisman37** [raspberrypi/tools#59]
Tried to make the usbboot tool on my raspberrypi and it threw this error.  Possibly something has changed lately with libusb??  To work around I edited the main.c file and replaced LIBUSB_LOG_LEVEL_WARNING with the number 2.  
This works, but I'm not sure if this is the best approach.

**Comment by ghollingworth** [comment]
Using clean Raspbian image and apt-get installing libusb-1.0-0-dev works fine

Closing unless we can find a method to reproduce?
