### ISSUE TITLE
Windows filesystem doesn't respect capitalization leaving multiple file collisons...

### ISSUE THREAD

**Issue by zafields** [raspberrypi/tools#63]
These two different files on your system collide on Windows:
```
...\raspberrypi-tools\arm-bcm2708\arm-bcm2708-linux-gnueabi\arm-bcm2708-linux-gnueabi\sysroot\usr\include\linux\netfilter\xt_DSCP.h
...\raspberrypi-tools\arm-bcm2708\arm-bcm2708-linux-gnueabi\arm-bcm2708-linux-gnueabi\sysroot\usr\include\linux\netfilter\xt_dscp.h

```
I am attempting to cross compile for the Pi using CMAKE on Windows, but I can't even clone your tools. Please consider renaming the files with similar names in your next iteration.

**Comment by popcornmix** [comment]
Windows if not a suitable platform for dealing with linux tools.
The arm-bcm2708-linux-gnueabi compiler is linux only and won't run on linux.
Also we are not in control of the naming of the files - these come from gcc.

I'd suggest you install Ubuntu inside VirtualBox (on the windows machine).
