### ISSUE TITLE
Remove usbboot from this repository

### ISSUE THREAD

**Issue by tpetazzoni** [raspberrypi/tools#71]
Would it be possible to split the usbboot tool in a separate repository? It is a bit annoying to have to download the huge "tools" repository (with all its toolchains) only to get the usbboot tool. I recently created a package for Buildroot to build usbboot, and we don't care at all about the toolchains (since Buildroot builds its own), but having to download such a huge repository is somewhat annoying.

**Comment by ghollingworth** [comment]
Actually it already has been, checkout github.com/raspberrypi/usbboot.git

But good point, I hadn't removed it from here...

**Comment by tpetazzoni** [comment]
Great, thanks! So I've renamed this issue to "Remove usbboot from this repository".

**Comment by ghollingworth** [comment]
Which has already been done...

**Comment by tpetazzoni** [comment]
Excellent, thanks! Issue closed then!
