### ISSUE TITLE
toolchain install 

### ISSUE THREAD

**Issue by samimash** [raspberrypi/tools#77]
how i can install the [toolchain](https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64) using terminal?
i am running ubuntu 14.04

**Comment by pelwell** [comment]
See https://www.raspberrypi.org/documentation/linux/kernel/building.md, under the "Cross-compiling" heading.
