### ISSUE TITLE
Error: scalar out of range for multiply instruction

### ISSUE THREAD

**Issue by madsu** [raspberrypi/tools#91]
/tmp/ccUMr7p9.s:220: Error: scalar out of range for multiply instruction -- `vmlal.s16 q1,d11,d16[0]'
/tmp/ccUMr7p9.s:221: Error: scalar out of range for multiply instruction -- `vmlal.s16 q0,d12,d16[1]'
/tmp/ccUMr7p9.s:222: Error: scalar out of range for multiply instruction -- `vmlal.s16 q1,d13,d16[1]'

I don't know what's wrong with this, the syntax seems right.

**Comment by JamesH65** [comment]
This is off topic for this github issue tracker. Please post your question on the forums, the bare metal section is probably the best place.
